- id: turn_on_entry_lights_arrival
  alias: Turn on entry lights when I arrive at night
  description: ''
  trigger:
  - platform: device
    device_id: 442f07fb47fb8d5df817f75fc8eb9b46
    domain: cover
    entity_id: cover.garage_door_1
    type: opening
  - platform: device
    device_id: 56b4edbbe4528c577c61ab17051f08f3
    domain: cover
    entity_id: cover.garage_door_2
    type: opening
  - platform: device
    device_id: 442f07fb47fb8d5df817f75fc8eb9b46
    domain: cover
    entity_id: cover.garage_door_1
    type: opened
  - platform: device
    device_id: 56b4edbbe4528c577c61ab17051f08f3
    domain: cover
    entity_id: cover.garage_door_2
    type: opened
  condition:
  - condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
  - service: script.entry_lights_on_from_garage
    data: {}
- id: turn_on_entry_lights_garage
  alias: Turn on entry lights from garage entry switch
  trigger:
  - entity_id: input_boolean.garage_entry
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      stop_actions: true
    service: automation.turn_off
    target:
      entity_id: automation.turn_on_entry_lights_from_kitchen_entry_switch
  - service: script.entry_lights_on_from_garage
    data: {}
  - data: {}
    entity_id: automation.turn_on_entry_lights_from_kitchen_entry_switch
    service: automation.turn_on
  mode: single
- id: turn_on_entry_lights_kitchen
  alias: Turn on entry lights from kitchen entry switch
  trigger:
  - platform: state
    entity_id: switch.kitchen_entry_56
    from: 'off'
    to: 'on'
  action:
  - data:
      stop_actions: true
    service: automation.turn_off
    target:
      entity_id: automation.turn_on_entry_lights_from_garage_entry_switch
  - service: script.entry_lights_on
    data: {}
  - data: {}
    entity_id: automation.turn_on_entry_lights_from_garage_entry_switch
    service: automation.turn_on
- id: turn_off_entry_lights_garage
  alias: Turn off entry lights from garage entry switch
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    entity_id: input_boolean.garage_entry
  action:
  - data:
      stop_actions: true
    service: automation.turn_off
    target:
      entity_id: automation.turn_off_entry_lights_from_kitchen_entry_switch
  - service: script.entry_lights_off
    data: {}
  - service: switch.turn_off
    data:
      entity_id: switch.hallway_overhead_5
  - data: {}
    entity_id: automation.turn_off_entry_lights_from_kitchen_entry_switch
    service: automation.turn_on
- id: turn_off_entry_lights_kitchen
  alias: Turn off entry lights from kitchen entry switch
  trigger:
  - platform: state
    entity_id: switch.kitchen_entry_56
    from: 'on'
    to: 'off'
  action:
  - data:
      stop_actions: true
    service: automation.turn_off
    target:
      entity_id: automation.turn_off_entry_lights_from_garage_entry_switch
  - service: script.entry_lights_off
    data: {}
  - data: {}
    entity_id: automation.turn_off_entry_lights_from_garage_entry_switch
    service: automation.turn_on
- id: turn_on_towel_warmer_weekday_mornings
  alias: Turn on towel warmer weekday mornings
  trigger:
  - platform: time
    at: 05:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    before: 00:00:00
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.towel_warmer_53
- id: turn_off_towel_warmer_weekday_mornings
  alias: Turn off towel warmer weekday mornings
  trigger:
  - platform: time
    at: 09:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    before: 00:00:00
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.towel_warmer_53
- id: turn_on_towel_warmer_weekend_mornings
  alias: Turn on towel warmer weekend mornings
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: time
    weekday:
    - sat
    - sun
    before: 00:00:00
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.towel_warmer_53
- id: turn_off_towel_warmer_weekend_mornings
  alias: Turn off towel warmer weekend mornings
  trigger:
  - platform: time
    at: '12:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
    before: 00:00:00
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.towel_warmer_53
- id: '1589936680579'
  alias: turn_on_outdoor_lights_at_dusk
  description: Turn on outdoor lights at dusk
  trigger:
  - below: '2'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition: []
  action:
  - data: {}
    service: switch.turn_on
    target:
      entity_id:
      - switch.patio_lights_49
  - data: {}
    entity_id: switch.patio_tree_spots_57
    service: switch.turn_on
  - data: {}
    entity_id: light.front_porch_light_48
    service: light.turn_on
    enabled: true
  mode: single
- id: '1589937131228'
  alias: turn_off_outdoor_lights_at_bedtime
  description: Turn off outdoor lights at bedtime
  trigger:
  - at: '23:59:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: switch.turn_off
    target:
      entity_id:
      - switch.patio_lights_49
  - data: {}
    entity_id: switch.patio_tree_spots_57
    service: switch.turn_off
  - data: {}
    entity_id: light.front_porch_light_48
    service: light.turn_off
  mode: single
- id: '1607698084703'
  alias: Update Google Assistant at HA startup
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: google_assistant.request_sync
    data: {}
  mode: single
- id: simulate_arrival
  alias: Simulate arrival
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: armed_away
  - platform: sun
    event: sunset
  - platform: event
    event_type: event_simulate_arrival
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: time
      before: '22:00:00'
    - condition: state
      entity_id: alarm_control_panel.abode_alarm
      state: armed_away
  action:
  - delay: 00:{{ (range(10, 45) | random) }}:00
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.garage_entry
  - delay: 00:{{ (range(2, 10) | random) }}:00
  - event: event_simulate_arrival_off
  - event: event_simulate_arrival
- id: simulate_arrival_off
  alias: Simulate arrival off
  trigger:
  - platform: event
    event_type: event_simulate_arrival_off
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode_alarm
    state: armed_away
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.garage_entry
- id: simulate_kitchen_presence
  alias: Simulate kitchen presence
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: armed_away
  - platform: time
    at: '18:01:00'
  - platform: time
    at: 05:01:00
  - platform: event
    event_type: event_simulate_kitchen_presence
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: time
        after: '18:00:00'
      - condition: time
        before: '22:00:00'
      - condition: state
        entity_id: alarm_control_panel.abode_alarm
        state: armed_away
    - condition: and
      conditions:
      - condition: time
        after: 05:00:00
      - condition: time
        before: 09:00:00
      - condition: state
        entity_id: alarm_control_panel.abode_alarm
        state: armed_away
  action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen_pendants_9
  - delay: 00:{{ (range(10, 50) | random) }}:00
  - event: event_simulate_kitchen_presence_off
  - delay: 00:{{ (range(2, 20) | random) }}:00
  - event: event_simulate_kitchen_presence
- id: simulate_kitchen_presence_off
  alias: Simulate kitchen presence off
  trigger:
  - platform: event
    event_type: event_simulate_kitchen_presence_off
  condition:
    condition: state
    entity_id: alarm_control_panel.abode_alarm
    state: armed_away
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_pendants_9
- id: simulate_upstairs_presence
  alias: Simulate upstairs presence
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: armed_away
  - platform: time
    at: '18:01:00'
  - platform: time
    at: 05:01:00
  - platform: event
    event_type: event_simulate_upstairs_presence
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: time
        after: '18:00:00'
      - condition: time
        before: '23:00:00'
      - condition: state
        entity_id: alarm_control_panel.abode_alarm
        state: armed_away
    - condition: and
      conditions:
      - condition: time
        after: 05:00:00
      - condition: time
        before: 09:00:00
      - condition: state
        entity_id: alarm_control_panel.abode_alarm
        state: armed_away
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.stairwell_lights_24
  - delay: 00:{{ (range(5, 15) | random) }}:00
  - event: event_simulate_upstairs_presence_off
  - delay: 00:{{ (range(5, 25) | random) }}:00
  - event: event_simulate_upstairs_presence
- id: simulate_upstairs_presence_off
  alias: Simulate upstairs presence off
  trigger:
  - platform: event
    event_type: event_simulate_upstairs_presence_off
  condition:
    condition: state
    entity_id: alarm_control_panel.abode_alarm
    state: armed_away
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.stairwell_lights_24
- id: '1632597804453'
  alias: Auto-close garage door 1
  description: Auto-close garage door 1 when open for 5 minutes from 9:00PM to 7:00AM
  trigger:
  - platform: state
    entity_id: cover.garage_door_1
    to: open
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: time
    after: '21:00:00'
    before: 07:00:00
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door_1
  - service: notify.notify_events
    data:
      message: Garage door 1 automatically closed
  mode: single
- id: '1632599500825'
  alias: Auto-close garage door 2 when open for 5 minutes from 9:00PM to 7:00AM
  description: ''
  trigger:
  - platform: state
    entity_id: cover.garage_door_2
    to: open
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: time
    after: '21:00:00'
    before: 07:00:00
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door_2
  - service: notify.notify_events
    data:
      message: Garage door 2 automatically closed
  mode: single
- id: '1670800960135'
  alias: Turn on humidifier when alarm is armed away
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.abode_alarm
    to: armed_away
  condition: []
  action:
  - service: script.turn_on_humidifier
    data: {}
  mode: single
- id: '1670801146205'
  alias: Turn off humidifier when I disarm the alarm
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.abode_alarm
    to: disarmed
    from: armed_away
  condition: []
  action:
  - service: script.turn_off_humidifier
    data: {}
  mode: single
- id: '1700944549387'
  alias: Reset Bar Sink Light
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: e4b724e0861282dedd32e7da64d0369d
    entity_id: 0e8c23020a37770e04a5658a16f5b714
    domain: light
  condition: []
  action:
  - service: pyscript.change_scene
    data:
      deviceId: '{{ state_attr(''light.fixturesmart_v3_0'', ''deviceId'') }}'
      scene: working
  mode: single
- id: '1700946390271'
  alias: Reset Range Light Left
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 9dd95867dceb79471082266db9796f4c
    entity_id: 44bf0dc3f2f9af9fb929b81af3eb2061
    domain: light
  condition: []
  action:
  - service: pyscript.change_scene
    data:
      deviceId: '{{ state_attr(''light.under_cabinet_light'', ''deviceId'') }}'
      scene: working
  mode: single
- id: '1700946603582'
  alias: Reset Range Light Right
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 65733c61fcb51df840b5bc159becee52
    entity_id: 2ff0ae5182de066e1f22111ba56578a9
    domain: light
  condition: []
  action:
  - service: pyscript.change_scene
    data:
      deviceId: '{{ state_attr(''light.under_cabinet_light_2'', ''deviceId'') }}'
      scene: working
  mode: single
