homeassistant:

  customize: !include customizations.yaml

# Enables logging
logger:
  default: warning
#  logs:
#    homeassistant.components.alert: debug
#    homeassistant.components.smtp: debug
#    homeassistant.components.notify: debug
#    homeassistant.components.device_tracker: debug

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables the configuration component
config:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# history recording
recorder:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google_translate

system_health:

vera:
  vera_controller_url: !secret vera_controller_url

ecobee:
  api_key: !secret ecobee_api_key

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: auto

notify_events:
  token: !secret notify_events_token

owntracks:
  max_gps_accuracy: !secret device_tracker_max_gps_accuracy
  waypoints: true
  waypoint_whitelist:
    - jon
    - ram
  events_only: false

map:

google_assistant:
  project_id: !secret google_project_id
  service_account: !include SERVICE_ACCOUNT.json

media_player:
  - platform: kodi
    host: !secret kodi_host
    port: !secret kodi_port

cover: !include covers.yaml
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
notify: !include notify.yaml
alert: !include alert.yaml
sensor: !include sensors.yaml

