homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone_home
  customize: !include customizations.yaml

# Enables logging
logger:
  default: info

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables the configuration component
config:

http:
#  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# history recording
recorder:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

vera:
  vera_controller_url: !secret vera_controller_url

ecobee:
  api_key: !secret ecobee_api_key

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: !secret device_tracker_platform
    max_gps_accuracy: !secret device_tracker_max_gps_accuracy
    waypoints: True
    waypoint_whitelist:
      - jon
      - ram

map:

google_assistant:
  project_id: !secret google_project_id
  client_id: !secret google_client_id
  access_token: !secret google_access_token
  agent_user_id: !secret google_agent_user_id
  api_key: !secret google_api_key

media_player:
  - platform: kodi
    host: !secret kodi_host
    port: !secret kodi_port

cover: !include covers.yaml
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
notify: !include notify.yaml
alert: !include alert.yaml
sensor: !include sensors.yaml

